### ISSUE TITLE
KeyError: 'score'

### ISSUE THREAD

**Issue by MesteMonokrom** [buluba89/Yatcobot#10]
Hi! Loving the bot so far, though I'm getting a couple of errors lately.

Last night it was working fine. I stopped the bot overnight, and continued in the morning. This was when these errors began.

I deleted the Yatcobot folder and git-cloned it again in case something borked when I stopped the bot, but it still happens.

https://s9.postimg.org/scf95e7xr/Screenshot_20180129-080227.png (apologies for the screenshot rather than a copy-paste. Termux couldn't copy the right parts of it)

**Comment by MesteMonokrom** [comment]
Also getting KeyError: 'full_text', which shows in the screenshot.

**Comment by Tinismo** [comment]
Try to delete (line 44) logger.debug("Tweet score: {}".format(post['score'])) in Yatcobot/bot.py

**Comment by MesteMonokrom** [comment]
That *might* have fixed it; there are still some errors now but it's attempting to retweet previously retweeted posts at the minute, which was more than it was doing earlier.

I'll let it run for a bit to see if it successfully retweets any new ones.

**Comment by MesteMonokrom** [comment]
Yep, that solved it. Thank you!

**Comment by buluba89** [comment]
Just reopening this to remember to fix this when i have time

**Comment by buluba89** [comment]
The problem was that when it encountered a quoted tweet it was getting the old not extended tweets.
Fixed with 822104ab017ee9e82ebb1e4cf59c909d90e9b7d3
