### ISSUE TITLE
Please add the friends tag function

### ISSUE THREAD

**Issue by ozhenn** [buluba89/Yatcobot#11]
<3

**Comment by buluba89** [comment]
I dont have a lot of time now, but in about two week i will have more free time. In the meantime it would be helpfull if you could share some sample posts that require a friends tag to have as an example.

Thanks !

**Comment by ozhenn** [comment]
Hello.
This tweet u cant us as example:
https://twitter.com/OfficialBoltgg/status/963618845691756545

Here need to tag two friends,but sometimes need to tag 3 or 4.

I hope u understand. Thank YOU! <3

**Comment by buluba89** [comment]
@ozhenn 
This feature is now implemented on the dev branch. If you are still interested please try it out!

Thanks
