### ISSUE TITLE
Notifier email

### ISSUE THREAD

**Issue by nivong** [buluba89/Yatcobot#18]
Hi @buluba89 
Just made this change, I do not know how to test this real quick with your test environment so can you have a look?
https://github.com/nivong/Yatcobot/commit/2e2757874a600cd151f77b3cb705f03fe3101ec7

**Comment by buluba89** [comment]
@nivong 
The "sending mail" part looks ok, but you shouldnt edit the abstractclass. Abstract classes are there to define an interface. Instead you should subclass the abstract class and define your logic there. 
But i will use your logic to create a mail notifier.
Come back in half an hour :P

**Comment by buluba89** [comment]
@nivong 
Done! 
For now its on the dev branch. Test it and report back !

**Comment by nivong** [comment]
working fine, thanks! Opening an new issue :P
