### ISSUE TITLE
Tag a friend multilanguage

### ISSUE THREAD

**Issue by nivong** [buluba89/Yatcobot#19]
Since I am dutch I only want dutch win tweets. Tag a friend is now only english. For example:
https://twitter.com/Zynteox/status/979743950981484545
Dutch:
Tag een vriend
(translated)
Tag a friend
is it possible to make this multilanguage ?

**Comment by buluba89** [comment]
@nivong 
Yes!
I will add tag and friend keywords in the config

**Comment by buluba89** [comment]
@nivong 
Added config parameters for tag, friend and number keywords with 0b3294ddbdcea994db7d2ec6117b08e237b3946f
Please try it out and report any issues

Thanks!
