### ISSUE TITLE
program does not work for me

### ISSUE THREAD

**Issue by biglegend** [buluba89/Yatcobot#22]
i put in all the right api keys,
i run it by just clicking the bot like it says in the post
im using windows 10

**Comment by buluba89** [comment]
You double click the yatcobot.py file ? 
Its a terminal application, double clicking isnt goin to run it.

**Comment by biglegend** [comment]
yes i did, sorry idk much about this my bad.

**Comment by buluba89** [comment]
If you are somewhat familiar with terminal you can set it up
I dont use windows, so i cant guide you through step by step.
You can start by installing [anaconda](https://www.anaconda.com/download/#windows) python3.6 version

**Comment by buluba89** [comment]
Nice, good job
This error means that it cant find your configuration file or that you didnt set the api keys. Make sure that the config.yml exists in your current directory

**Comment by biglegend** [comment]
oww i renamed the file to "sample.yaml" instead of "config.yaml" not so smart, but the program runs now! how fast does it retweet? because since i started it did only retweet 1 tweet its been like 3 mins :$

**Comment by buluba89** [comment]
there is a config option
```yaml
  scheduler
    retweet_interval: 600
```
this is the default value and it means every 600 seconds

check the docs for more options [https://yatcobot.readthedocs.io/en/master/config.html](https://yatcobot.readthedocs.io/en/master/config.html)

**Comment by biglegend** [comment]
okay thank you so much for your time i appreciate it!!
