### ISSUE TITLE
How could I run this on a hosting service so I do not have to keep running it locally?

### ISSUE THREAD

**Issue by DevinParentice** [buluba89/Yatcobot#23]
I have tried Heroku and AWS' EC2 but I have been having trouble with each of them. Do you have any tips on how I could host this somewhere so I do not have to keep my machine on 24/7 and have this running in the background? Thanks!

**Comment by buluba89** [comment]
Hello @DevinParentice 
What is the trouble that you are facing ?(some logs would be helpful)

EC2 should be straight forward to configure, its a linux vm afterall. 
I have never used heroku, so i dont think i can help. Maybe using the docker image is easier there

**Comment by DevinParentice** [comment]
Hi,

So I connected to the EC2 with PuTTY and installed yatcobot with pip, I then transferred and overwrote the config file with my own through FileZilla. Though, when I travel to the config folder and type "yatcobot" to run the program as I do on my local machine, it says that it is not a valid command.

**Comment by buluba89** [comment]
Maybe /usr/local/bin (tha is the default installation path of pip) is not in $PATH. Or you forgot to use sudo
In ubuntu the correct command is:
```
sudo pip3 install yatcobot
```
A alternative is to just clone it and use it from the repo
```
sudo apt install git python3-pip
git clone https://github.com/buluba89/Yatcobot.git
cd yatcobot
sudo pip3 install -r requirements.txt
./yatcobot.py
```

**Comment by DevinParentice** [comment]
For whatever reason when I tried it again it worked. Thanks for the help anyways! Also just for anyone reading this in the future, use the command "nohup yatcobot > /dev/null 2>&1 &" (without the quotes). nohup allows the bot to run even when you close the PuTTY connection, which would defeat the purpose of hosting it on AWS in the first place. Thanks again!
