### ISSUE TITLE
Minimum RT limit

### ISSUE THREAD

**Issue by Donokami** [buluba89/Yatcobot#7]
Hello,
And thanks for your amazing work.
Would it be possible to add a function that don't retweet contests that have less than X (example: 10) retweets, to avoid retweeting fake contests ?
Thanks.

**Comment by buluba89** [comment]
Right now, posts with more retweets get some priority over others with less (combined with some other parameters as post age and keywords )
It would be easy to add a filter based on retweets count, but the config file is starting to get very messy, json was convenient at the time but its not pretty. 
So i am thinking to change the config to another format (probably yaml) and then start adding features like that

**Comment by buluba89** [comment]
@Donokami 
If you are still interested i implemented this functionality (better late than never :-P ).

It is in the dev branch for now, but soon will be in master.

Be aware that you must migrate the config to the new config!
