### ISSUE TITLE
Multiple follow

### ISSUE THREAD

**Issue by Donokami** [buluba89/Yatcobot#8]
Hi,
In my country we have a lot of contests that need to follow 2 accounts to be accepted as a participant.
If a contest's tweet has multiple @mentions, would it be possible to follow all these accounts, with a timing between the follow to avoid getting a rate limit?
Thanks.
PS: Could it be possible to add the support of 280 characters tweets? Thanks.

**Comment by buluba89** [comment]
Hello
280 characters tweets was added by @Tinismo so it should be ok.

I will take a look into multiple mentions soon!

**Comment by buluba89** [comment]
@Donokami 
This feature is now implemented!
